@file:OptIn(ExperimentalWasmDsl::class)

import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    kotlin("multiplatform")
    id("maven-publish")
    signing
}
kotlin {
    iosX64()
    iosArm64()
    iosSimulatorArm64()

    js(IR) {
        browser()
    }

    wasmJs {
        browser()
    }

    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8)
        }
    }

    // Define source sets and add dependencies for each target
    sourceSets {

        val commonMain by getting {
            kotlin.srcDir("src/commonMain/kotlin")
            dependencies {
                // Add any dependencies needed for the common code

            }
        }

        val commonTest by getting
        val jvmMain by getting
        val jvmTest by getting
        val jsMain by getting
        val jsTest by getting
        val wasmJsMain by getting
        val wasmJsTest by getting

    }
}

val javadocJar by tasks.registering(Jar::class) {
    archiveClassifier.set("javadoc")
}

publishing {
    publications {
        withType<MavenPublication>().configureEach {

            groupId = "com.blu3berry.kraft"
            version = (project.properties["kraft.version"] as? String) ?: "0.0.0-SNAPSHOT"

            artifact(javadocJar)

            when (name) {
                "kotlinMultiplatform" -> {
                    artifactId = "kraft-annotations"
                }
                "jvm" -> {
                    artifactId = "kraft-annotations-jvm"
                }
                "iosX64" -> {
                    artifactId = "kraft-annotations-iosx64"
                }
                "iosArm64" -> {
                    artifactId = "kraft-annotations-iosarm64"
                }
                "iosSimulatorArm64" -> {
                    artifactId = "kraft-annotations-iossimarm64"
                }
                "js" -> {
                    artifactId = "kraft-annotations-js"
                }
                "wasmJs" -> {
                    artifactId = "kraft-annotations-wasmjs"
                }
                else -> {
                    // metadata, sources, etc. will be autogenerated correctly
                }
            }

            pom {
                name.set("kraft-annotations")
                description.set("Annotation definitions for the Kraft compile-time mapper generator")
                url.set("https://github.com/blu3berry-why/Kraft")
                licenses {
                    license {
                        name.set("Apache-2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0")
                    }
                }
                developers {
                    developer {
                        id.set("blu3berry-why")
                        name.set("blu3berry")
                        url.set("https://github.com/blu3berry-why")
                    }
                }
                scm {
                    url.set("https://github.com/blu3berry-why/Kraft")
                    connection.set("scm:git:git://github.com/blu3berry-why/Kraft.git")
                    developerConnection.set("scm:git:ssh://github.com/blu3berry-why/Kraft.git")
                }
            }
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/blu3berry-why/Kraft")

            credentials {
                username = project.findProperty("gpr.user") as String?
                password = project.findProperty("gpr.token") as String?
            }
        }
        maven {
            name = "MavenCentral"
            url = uri("https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/")

            credentials {
                username = findProperty("maven.central.username") as String?
                password = findProperty("maven.central.password") as String?
            }
        }
    }
}

signing {
    useGpgCmd()
    isRequired = findProperty("signing.gnupg.keyName") != null
    sign(publishing.publications)
}

tasks.withType<AbstractPublishToMaven>().configureEach {
    mustRunAfter(tasks.withType<Sign>())
}
