
plugins {
    kotlin("multiplatform")
    id("maven-publish")
}
kotlin {
    jvm()
    iosX64()
    iosArm64()
    iosSimulatorArm64()

    // Define source sets and add dependencies for each target
    sourceSets {

        val commonMain by getting {
            kotlin.srcDir("src/commonMain/kotlin")
            dependencies {
                // Add any dependencies needed for the common code

            }
        }

        val commonTest by getting
        val jvmMain by getting
        val jvmTest by getting

    }
}

publishing {
    publications {
        withType<MavenPublication>().configureEach {

            groupId = "hu.nova.blu3berry.kraft"
            version = project.properties["kraft.version"] as String

            when (name) {
                "kotlinMultiplatform" -> {
                    artifactId = "kraft-annotations"
                }
                "jvm" -> {
                    artifactId = "kraft-annotations-jvm"
                }
                "iosX64" -> {
                    artifactId = "kraft-annotations-iosx64"
                }
                "iosArm64" -> {
                    artifactId = "kraft-annotations-iosarm64"
                }
                "iosSimulatorArm64" -> {
                    artifactId = "kraft-annotations-iossimarm64"
                }
                else -> {
                    // metadata, sources, etc. will be autogenerated correctly
                }
            }
        }

    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/blu3berry-why/Kraft")

            credentials {
                username = project.findProperty("gpr.user") as String?
                password = project.findProperty("gpr.token") as String?
            }
        }
    }
}