@file:OptIn(ExperimentalWasmDsl::class)

import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    kotlin("multiplatform")
    id("maven-publish")
}
kotlin {
    iosX64()
    iosArm64()
    iosSimulatorArm64()

    js(IR) {
        browser()
    }

    wasmJs {
        browser()
    }

    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    // Define source sets and add dependencies for each target
    sourceSets {

        val commonMain by getting {
            kotlin.srcDir("src/commonMain/kotlin")
            dependencies {
                // Add any dependencies needed for the common code

            }
        }

        val commonTest by getting
        val jvmMain by getting
        val jvmTest by getting
        val jsMain by getting
        val jsTest by getting
        val wasmJsMain by getting
        val wasmJsTest by getting

    }
}

publishing {
    publications {
        withType<MavenPublication>().configureEach {

            groupId = "hu.nova.blu3berry.kraft"
            version = (project.properties["kraft.version"] as? String) ?: "0.0.0-SNAPSHOT"

            when (name) {
                "kotlinMultiplatform" -> {
                    artifactId = "kraft-annotations"
                }
                "jvm" -> {
                    artifactId = "kraft-annotations-jvm"
                }
                "iosX64" -> {
                    artifactId = "kraft-annotations-iosx64"
                }
                "iosArm64" -> {
                    artifactId = "kraft-annotations-iosarm64"
                }
                "iosSimulatorArm64" -> {
                    artifactId = "kraft-annotations-iossimarm64"
                }
                "js" -> {
                    artifactId = "kraft-annotations-js"
                }
                "wasmJs" -> {
                    artifactId = "kraft-annotations-wasmjs"
                }
                else -> {
                    // metadata, sources, etc. will be autogenerated correctly
                }
            }
        }

    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/blu3berry-why/Kraft")

            credentials {
                username = project.findProperty("gpr.user") as String?
                password = project.findProperty("gpr.token") as String?
            }
        }
    }
}