package com.blu3berry.kraft.processor.scanner

import com.google.devtools.ksp.KspExperimental
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.Nullability
import com.google.devtools.ksp.symbol.Origin
import com.blu3berry.kraft.model.scan.ConverterTypeKey
import com.blu3berry.kraft.model.scan.GlobalConverterRegistry
import com.blu3berry.kraft.processor.util.KraftKspConstants

/**
 * Scans the classpath for `@KraftConverterDelegate`-annotated extension functions
 * generated by upstream Kraft modules into package
 * [KraftKspConstants.GENERATED_REGISTRY_PACKAGE].
 *
 * Each upstream module publishes one delegate file containing thin extension wrappers
 * around its `@KraftConverter` functions. Delegates are top-level extensions, so KSP's
 * `Resolver.getDeclarationsFromPackage(...)` indexes them across the classpath without
 * a brute-force scan.
 *
 * Ambiguity *between* classpath modules — two different modules registering the same
 * `(source, target)` pair — produces a KSP error pointing at both delegates. Same-module
 * `@KraftConverter` overrides classpath delegates silently; that merge happens in the
 * caller, not here.
 */
class ClasspathConverterScanner(
    private val resolver: Resolver,
    private val logger: KSPLogger
) {
    @OptIn(KspExperimental::class)
    fun scan(): GlobalConverterRegistry {
        val packageName = KraftKspConstants.GENERATED_REGISTRY_PACKAGE
        val delegates = resolver.getDeclarationsFromPackage(packageName)
            .filterIsInstance<KSFunctionDeclaration>()
            .filter { fn -> fn.origin == Origin.KOTLIN_LIB || fn.origin == Origin.JAVA_LIB }
            .filter { fn -> fn.annotations.any(::isDelegateAnnotation) }
            .toList()

        if (delegates.isEmpty()) return GlobalConverterRegistry.EMPTY

        val entries = mutableMapOf<ConverterTypeKey, KSFunctionDeclaration>()
        for (fn in delegates) {
            registerDelegate(fn, entries)
        }
        return GlobalConverterRegistry(entries.toMap())
    }

    private fun isDelegateAnnotation(annotation: KSAnnotation): Boolean =
        annotation.annotationType.resolve().declaration.qualifiedName?.asString() ==
            KraftKspConstants.FQ_KRAFT_CONVERTER_DELEGATE

    private fun registerDelegate(
        fn: KSFunctionDeclaration,
        entries: MutableMap<ConverterTypeKey, KSFunctionDeclaration>
    ) {
        val receiver = fn.extensionReceiver?.resolve() ?: return
        val returnType = fn.returnType?.resolve() ?: return
        val key = buildKey(receiver, returnType) ?: return

        val existing = entries[key]
        if (existing != null) {
            reportClasspathAmbiguity(key, existing, fn)
            return
        }
        entries[key] = fn
    }

    private fun buildKey(sourceType: KSType, targetType: KSType): ConverterTypeKey? {
        val sourceDecl = sourceType.declaration as? KSClassDeclaration ?: return null
        val targetDecl = targetType.declaration as? KSClassDeclaration ?: return null
        val sourceFq = sourceDecl.qualifiedName?.asString() ?: return null
        val targetFq = targetDecl.qualifiedName?.asString() ?: return null
        return ConverterTypeKey(
            sourceFqName = sourceFq,
            sourceNullable = sourceType.nullability == Nullability.NULLABLE,
            targetFqName = targetFq,
            targetNullable = targetType.nullability == Nullability.NULLABLE
        )
    }

    private fun reportClasspathAmbiguity(
        key: ConverterTypeKey,
        existing: KSFunctionDeclaration,
        duplicate: KSFunctionDeclaration
    ) {
        val source = "${key.sourceFqName}${if (key.sourceNullable) "?" else ""}"
        val target = "${key.targetFqName}${if (key.targetNullable) "?" else ""}"
        val existingName = existing.qualifiedName?.asString() ?: existing.simpleName.asString()
        val duplicateName = duplicate.qualifiedName?.asString() ?: duplicate.simpleName.asString()
        logger.error(
            "Ambiguous @KraftConverter on the classpath for ($source → $target): " +
                "registered by '$existingName' and '$duplicateName'. " +
                "Disambiguate by adding a same-module @KraftConverter or a per-property @MapUsing.",
            duplicate
        )
    }
}
