package com.blu3berry.kraft.processor.scanner

import com.google.devtools.ksp.KspExperimental
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.Origin
import com.blu3berry.kraft.model.scan.ConverterEntry
import com.blu3berry.kraft.model.scan.ConverterTypeKey
import com.blu3berry.kraft.model.scan.GlobalConverterRegistry
import com.blu3berry.kraft.processor.util.KraftKspConstants
import com.blu3berry.kraft.processor.util.buildConverterTypeKey

/**
 * Scans the classpath for `@KraftConverterDelegate`-annotated extension functions
 * generated by upstream Kraft modules into package
 * [KraftKspConstants.GENERATED_REGISTRY_PACKAGE].
 *
 * Each upstream module publishes one delegate file containing thin extension wrappers
 * around its `@KraftConverter` functions. Delegates are top-level extensions, so KSP's
 * `Resolver.getDeclarationsFromPackage(...)` indexes them across the classpath without
 * a brute-force scan.
 *
 * Ambiguity *between* classpath modules — two different modules registering the same
 * `(source, target)` pair — produces a KSP error pointing at both delegates. Same-module
 * `@KraftConverter` overrides classpath delegates silently; that merge happens in the
 * caller, not here.
 */
class ClasspathConverterScanner(
    private val resolver: Resolver,
    private val logger: KSPLogger
) {
    /**
     * @param sameModuleKeys keys already registered by the same-module
     *                       [GlobalConverterScanner]. Pairs covered locally are
     *                       silently dropped from the classpath registry — the
     *                       local override wins and any upstream-vs-upstream
     *                       ambiguity for those pairs is not reported, since the
     *                       user has already disambiguated via a same-module
     *                       `@KraftConverter`.
     */
    @OptIn(KspExperimental::class)
    fun scan(sameModuleKeys: Set<ConverterTypeKey> = emptySet()): GlobalConverterRegistry {
        val packageName = KraftKspConstants.GENERATED_REGISTRY_PACKAGE
        val delegates = resolver.getDeclarationsFromPackage(packageName)
            .filterIsInstance<KSFunctionDeclaration>()
            .filter { fn -> fn.origin == Origin.KOTLIN_LIB || fn.origin == Origin.JAVA_LIB }
            .filter { fn -> fn.annotations.any(::isDelegateAnnotation) }
            .toList()

        if (delegates.isEmpty()) return GlobalConverterRegistry.EMPTY

        val entries = mutableMapOf<ConverterTypeKey, ConverterEntry>()
        for (fn in delegates) {
            registerDelegate(fn, entries, sameModuleKeys)
        }
        return GlobalConverterRegistry(entries.toMap())
    }

    private fun isDelegateAnnotation(annotation: KSAnnotation): Boolean =
        annotation.annotationType.resolve().declaration.qualifiedName?.asString() ==
            KraftKspConstants.FQ_KRAFT_CONVERTER_DELEGATE

    private fun registerDelegate(
        fn: KSFunctionDeclaration,
        entries: MutableMap<ConverterTypeKey, ConverterEntry>,
        sameModuleKeys: Set<ConverterTypeKey>
    ) {
        val key = resolveDelegateKey(fn) ?: return

        // The local @KraftConverter shadows any upstream entry for this pair, so
        // we don't need to record (and certainly don't need to error on) classpath
        // duplicates that the user has already disambiguated locally.
        if (key in sameModuleKeys) return

        val existing = entries[key]
        if (existing != null) {
            // Classpath delegates are always discovered as KSFunctionDeclaration,
            // so existing must be Real here; report against the underlying function.
            if (existing is ConverterEntry.Real) reportClasspathAmbiguity(key, existing.function, fn)
        } else {
            entries[key] = ConverterEntry.Real(fn)
        }
    }

    private fun resolveDelegateKey(fn: KSFunctionDeclaration): ConverterTypeKey? {
        val receiver = fn.extensionReceiver?.resolve() ?: return null
        val returnType = fn.returnType?.resolve() ?: return null
        // Generic delegates aren't generated by GlobalConverterScanner (which rejects them),
        // but if an upstream module produced one, drop it silently — same v1 limitation applies.
        if (receiver.arguments.isNotEmpty() || returnType.arguments.isNotEmpty()) return null
        return buildConverterTypeKey(receiver, returnType)
    }

    private fun reportClasspathAmbiguity(
        key: ConverterTypeKey,
        existing: KSFunctionDeclaration,
        duplicate: KSFunctionDeclaration
    ) {
        val source = "${key.sourceFqName}${if (key.sourceNullable) "?" else ""}"
        val target = "${key.targetFqName}${if (key.targetNullable) "?" else ""}"
        val existingName = existing.qualifiedName?.asString() ?: existing.simpleName.asString()
        val duplicateName = duplicate.qualifiedName?.asString() ?: duplicate.simpleName.asString()
        logger.error(
            "Ambiguous @KraftConverter on the classpath for ($source → $target): " +
                "registered by '$existingName' and '$duplicateName'. " +
                "Disambiguate by adding a same-module @KraftConverter or a per-property @MapUsing.",
            duplicate
        )
    }
}
