package com.blu3berry.kraft.processor.scanner

import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.Origin
import com.blu3berry.kraft.model.scan.ConverterEntry
import com.blu3berry.kraft.model.scan.ConverterTypeKey
import com.blu3berry.kraft.processor.util.DelegateNaming
import com.blu3berry.kraft.processor.util.KraftKspConstants
import com.blu3berry.kraft.processor.util.buildConverterTypeKey

/**
 * Resolves `@KraftConverterDelegate` extension functions published by upstream Kraft
 * modules into package [KraftKspConstants.GENERATED_REGISTRY_PACKAGE].
 *
 * Discovery is purely by-name: the delegate's function name is a pure function of the
 * converter's type pair (see [DelegateNaming]), so for any unresolved pair the consumer
 * constructs the expected FQN and resolves it with `Resolver.getFunctionDeclarationsByName`.
 * That API crosses both JVM class-file classpaths and klib (KMP metadata) classpaths —
 * unlike package enumeration via `getDeclarationsFromPackage`, which returns nothing for
 * klib dependencies and was dropped for that reason.
 *
 * Consequences of by-name discovery:
 * - Producer and consumer modules must build with the **same Kraft version** — the name
 *   format is internal wiring and may change between releases. A mismatch (including
 *   artifacts published with Kraft ≤ 0.10.x, whose delegates use index-based names)
 *   degrades to "no converter found", never to wrong generated code.
 * - Lookup is lazy: it only runs for type pairs that no same-module converter resolved,
 *   so a local `@KraftConverter` shadows a classpath delegate simply by resolving first.
 * - Ambiguity *between* upstream modules — two modules registering the same pair — is
 *   detected because both emit the same delegate FQN and the by-name lookup returns all
 *   candidates; the error names both producing modules. Pairs that no mapper needs are
 *   never looked up, so an unused upstream conflict is not an error.
 */
class ClasspathConverterScanner(
    private val resolver: Resolver,
    private val logger: KSPLogger
) {
    private val byNameCache = mutableMapOf<ConverterTypeKey, ConverterEntry?>()

    /**
     * Resolves the classpath delegate for [key] by its deterministic name. Results
     * (including misses) are memoized per scanner instance, i.e. per processing round.
     * Misses are cached with an explicit containsKey check — getOrPut can't distinguish
     * a stored null from an absent key, so it would re-run the resolver query on every
     * miss.
     */
    fun lookupByName(key: ConverterTypeKey): ConverterEntry? {
        if (byNameCache.containsKey(key)) return byNameCache[key]
        return resolveByName(key).also { byNameCache[key] = it }
    }

    private fun resolveByName(key: ConverterTypeKey): ConverterEntry? {
        val fqName = "${KraftKspConstants.GENERATED_REGISTRY_PACKAGE}.${DelegateNaming.delegateNameFor(key)}"
        val matches = resolver
            .getFunctionDeclarationsByName(resolver.getKSNameFromString(fqName), includeTopLevel = true)
            .filter(::isLibraryDelegate)
            .filter { fn -> resolveDelegateKey(fn) == key }
            .toList()

        if (matches.size > 1) {
            reportClasspathAmbiguity(key, matches)
        }
        return matches.firstOrNull()?.let(ConverterEntry::Real)
    }

    private fun isLibraryDelegate(fn: KSFunctionDeclaration): Boolean =
        (fn.origin == Origin.KOTLIN_LIB || fn.origin == Origin.JAVA_LIB) &&
            fn.annotations.any(::isDelegateAnnotation)

    private fun isDelegateAnnotation(annotation: KSAnnotation): Boolean =
        annotation.annotationType.resolve().declaration.qualifiedName?.asString() ==
            KraftKspConstants.FQ_KRAFT_CONVERTER_DELEGATE

    private fun resolveDelegateKey(fn: KSFunctionDeclaration): ConverterTypeKey? {
        val receiver = fn.extensionReceiver?.resolve() ?: return null
        val returnType = fn.returnType?.resolve() ?: return null
        // Generic delegates aren't generated by GlobalConverterScanner (which rejects them),
        // but if an upstream module produced one, drop it silently — same v1 limitation applies.
        if (receiver.arguments.isNotEmpty() || returnType.arguments.isNotEmpty()) return null
        return buildConverterTypeKey(receiver, returnType)
    }

    /** Reports every conflicting module at once so the user fixes the conflict in one pass. */
    private fun reportClasspathAmbiguity(
        key: ConverterTypeKey,
        matches: List<KSFunctionDeclaration>
    ) {
        val source = "${key.sourceFqName}${if (key.sourceNullable) "?" else ""}"
        val target = "${key.targetFqName}${if (key.targetNullable) "?" else ""}"
        val registeredBy = matches.joinToString(" and ") { describeDelegate(it) }
        logger.error(
            "Ambiguous @KraftConverter on the classpath for ($source → $target): " +
                "registered by $registeredBy. " +
                "Disambiguate by adding a same-module @KraftConverter or a per-property @MapUsing.",
            matches.last()
        )
    }

    /**
     * Names the delegate's producing module when the delegate carries one. Delegates
     * for the same pair share the same function name by design, so the module id is
     * the only thing that distinguishes the two sides of an ambiguity report.
     */
    private fun describeDelegate(fn: KSFunctionDeclaration): String {
        val moduleId = fn.annotations.firstOrNull(::isDelegateAnnotation)
            ?.arguments
            ?.firstOrNull { it.name?.asString() == "moduleId" }
            ?.value as? String
        val fqName = fn.qualifiedName?.asString() ?: fn.simpleName.asString()
        return if (moduleId.isNullOrBlank()) "'$fqName'" else "Kraft module '$moduleId' ('$fqName')"
    }
}
