package com.blu3berry.kraft.processor.codegen.generator

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import com.blu3berry.kraft.model.scan.GlobalConverterRegistry
import com.blu3berry.kraft.processor.codegen.OptInMarker
import com.blu3berry.kraft.processor.codegen.OptInMarkerCollector
import com.blu3berry.kraft.processor.util.KraftKspConstants

/**
 * Emits a single Kotlin file at `kraft.generated.registry.Converters_<moduleId>.kt`
 * that re-exports every same-module `@KraftConverter` extension function as a
 * `@KraftConverterDelegate` thin wrapper.
 *
 * The wrapper exists purely so consuming KSP runs can discover the converters via
 * `Resolver.getDeclarationsFromPackage(...)` — KSP can't iterate `@KraftConverter`
 * annotations across the classpath, but it *can* iterate top-level declarations in a
 * known package. Each delegate trampolines to the user's original function so call
 * sites get the same runtime behavior.
 *
 * The file name suffix is `kraft.moduleId` when the processor option is set,
 * otherwise a deterministic hash of the sorted converter FQN list. Set the option in
 * Gradle when you have multiple modules contributing converters to the same
 * compilation classpath, otherwise different modules can collide on the same file
 * name and KSP will fail with "duplicate file" errors.
 */
class DelegateRegistryGenerator(
    private val logger: KSPLogger,
    private val moduleIdOption: String?
) {
    fun generate(registry: GlobalConverterRegistry, codeGenerator: CodeGenerator) {
        if (registry.entries.isEmpty()) return

        val converters = registry.entries.values.toList()
        val moduleSuffix = moduleIdOption?.let(::sanitize)
            ?: contentHash(converters)
        val fileName = "Converters_$moduleSuffix"
        val fileBuilder = FileSpec.builder(KraftKspConstants.GENERATED_REGISTRY_PACKAGE, fileName)
            .addFileComment("Generated by Kraft. Do not edit.")

        converters.forEachIndexed { index, fn ->
            fileBuilder.addFunction(buildDelegate(fn, index))
        }

        val originatingFiles = converters.mapNotNull { it.containingFile }.distinct()
        @Suppress("SpreadOperator")
        val deps = Dependencies(aggregating = true, *originatingFiles.toTypedArray())
        fileBuilder.build().writeTo(codeGenerator, deps)
        logger.info(
            "Generated @KraftConverterDelegate registry: " +
                "${KraftKspConstants.GENERATED_REGISTRY_PACKAGE}.$fileName " +
                "(${converters.size} converters)"
        )
    }

    private fun buildDelegate(original: KSFunctionDeclaration, index: Int): FunSpec {
        val receiverKsType = original.extensionReceiver!!.resolve()
        val returnKsType = original.returnType!!.resolve()
        val receiverType: TypeName = receiverKsType.toTypeName()
        val returnType: TypeName = returnKsType.toTypeName()

        val originalMember = MemberName(original.packageName.asString(), original.simpleName.asString())
        val delegateAnnotation = AnnotationSpec.builder(
            ClassName("com.blu3berry.kraft.config", "KraftConverterDelegate")
        ).build()

        val builder = FunSpec.builder(delegateName(original, index))
            .addModifiers(KModifier.PUBLIC)
            .addAnnotation(delegateAnnotation)
            .receiver(receiverType)
            .returns(returnType)
            .addStatement("return %M()", originalMember)

        optInAnnotation(collectMarkers(original, receiverKsType, returnKsType))?.let(builder::addAnnotation)
        return builder.build()
    }

    private fun collectMarkers(
        original: KSFunctionDeclaration,
        receiverType: KSType,
        returnType: KSType
    ): List<OptInMarker> {
        val targets = mutableListOf<KSAnnotated>(original)
        (receiverType.declaration as? KSClassDeclaration)?.let(targets::add)
        (returnType.declaration as? KSClassDeclaration)?.let(targets::add)
        return OptInMarkerCollector.collectFromAnnotated(targets)
    }

    @Suppress("SpreadOperator")
    private fun optInAnnotation(markers: List<OptInMarker>): AnnotationSpec? {
        if (markers.isEmpty()) return null
        val format = markers.joinToString(", ") { "%T::class" }
        val markerTypes = markers.map { ClassName(it.packageName, it.simpleName) }.toTypedArray()
        return AnnotationSpec.builder(ClassName("kotlin", "OptIn"))
            .addMember(format, *markerTypes)
            .build()
    }

    private fun delegateName(original: KSFunctionDeclaration, index: Int): String {
        val safeOriginal = original.simpleName.asString().replace(Regex("[^A-Za-z0-9_]"), "_")
        return "${safeOriginal}__kraft_delegate_$index"
    }

    private fun sanitize(raw: String): String =
        raw.replace(Regex("[^A-Za-z0-9_]"), "_").ifBlank { "module" }

    private fun contentHash(converters: List<KSFunctionDeclaration>): String {
        val sortedFqs = converters
            .mapNotNull { it.qualifiedName?.asString() ?: it.simpleName.asString() }
            .sorted()
            .joinToString("|")
        // Stable, short, no external dependency; collisions are tolerated because
        // duplicate file names within one module already imply the same converter set.
        return "%08x".format(sortedFqs.hashCode())
    }
}
