package com.blu3berry.kraft.processor.codegen.generator

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import com.blu3berry.kraft.model.scan.ConverterEntry
import com.blu3berry.kraft.model.scan.ConverterTypeKey
import com.blu3berry.kraft.model.scan.GlobalConverterRegistry
import com.blu3berry.kraft.processor.codegen.OptInMarker
import com.blu3berry.kraft.processor.codegen.OptInMarkerCollector
import com.blu3berry.kraft.processor.codegen.className
import com.blu3berry.kraft.processor.util.DelegateNaming
import com.blu3berry.kraft.processor.util.KraftKspConstants

/**
 * Emits a single Kotlin file at `kraft.generated.registry.Converters_<moduleId>.kt`
 * that re-exports every same-module `@KraftConverter` extension function as a
 * `@KraftConverterDelegate` thin wrapper.
 *
 * The wrapper exists purely so consuming KSP runs can discover the converters —
 * KSP can't iterate `@KraftConverter` annotations across the classpath. JVM consumers
 * enumerate the reserved package via `Resolver.getDeclarationsFromPackage(...)`; KMP
 * consumers can't (that API returns nothing for klib dependencies), so each delegate's
 * *name* is derived deterministically from its source/target type pair via
 * [DelegateNaming] and consumers resolve it directly with
 * `Resolver.getFunctionDeclarationsByName`. Each delegate trampolines to the user's
 * original function so call sites get the same runtime behavior.
 *
 * The file name suffix is `kraft.moduleId` when the processor option is set,
 * otherwise a deterministic hash of the sorted converter FQN list. Set the option in
 * Gradle when you have multiple modules contributing converters to the same
 * compilation classpath, otherwise different modules can collide on the same file
 * name and KSP will fail with "duplicate file" errors.
 */
class DelegateRegistryGenerator(
    private val logger: KSPLogger,
    private val moduleIdOption: String?
) {
    fun generate(registry: GlobalConverterRegistry, codeGenerator: CodeGenerator) {
        if (registry.entries.isEmpty()) return

        // Delegate names are derived from each entry's ConverterTypeKey, so they are
        // stable regardless of iteration order; sorting just keeps the generated file
        // content reproducible across rebuilds.
        val converters = registry.entries
            .toSortedMap(converterKeyComparator)
            .toList()
        val moduleSuffix = moduleIdOption?.let(::sanitize)
            ?: contentHash(converters.map { (_, entry) -> entry })
        val fileName = "Converters_$moduleSuffix"
        val fileBuilder = FileSpec.builder(KraftKspConstants.GENERATED_REGISTRY_PACKAGE, fileName)
            .addFileComment("Generated by Kraft. Do not edit.")

        for ((key, entry) in converters) {
            fileBuilder.addFunction(buildDelegate(key, entry))
        }

        val originatingFiles = collectOriginatingFiles(converters.map { (_, entry) -> entry })
        @Suppress("SpreadOperator")
        val deps = Dependencies(aggregating = true, *originatingFiles.toTypedArray())
        fileBuilder.build().writeTo(codeGenerator, deps)
        logger.info(
            "Generated @KraftConverterDelegate registry: " +
                "${KraftKspConstants.GENERATED_REGISTRY_PACKAGE}.$fileName " +
                "(${converters.size} converters)"
        )
    }

    private fun collectOriginatingFiles(entries: List<ConverterEntry>): List<KSFile> {
        val files = mutableListOf<KSFile>()
        for (entry in entries) {
            when (entry) {
                is ConverterEntry.Real -> entry.function.containingFile?.let(files::add)
                is ConverterEntry.Synthetic -> files.addAll(entry.originatingFiles)
            }
        }
        return files.distinct()
    }

    private fun buildDelegate(key: ConverterTypeKey, entry: ConverterEntry): FunSpec = when (entry) {
        is ConverterEntry.Real -> buildRealDelegate(key, entry.function)
        is ConverterEntry.Synthetic -> buildSyntheticDelegate(key, entry)
    }

    private fun buildRealDelegate(key: ConverterTypeKey, original: KSFunctionDeclaration): FunSpec {
        val receiverKsType = original.extensionReceiver!!.resolve()
        val returnKsType = original.returnType!!.resolve()
        val receiverType: TypeName = receiverKsType.toTypeName()
        val returnType: TypeName = returnKsType.toTypeName()

        val originalMember = MemberName(original.packageName.asString(), original.simpleName.asString())

        val builder = FunSpec.builder(DelegateNaming.delegateNameFor(key))
            .addModifiers(KModifier.PUBLIC)
            .addAnnotation(delegateAnnotation())
            .receiver(receiverType)
            .returns(returnType)
            .addStatement("return %M()", originalMember)

        optInAnnotation(collectMarkers(original, receiverKsType, returnKsType))?.let(builder::addAnnotation)
        return builder.build()
    }

    /**
     * Builds the delegate wrapper for a synthetic converter (currently
     * `@MapEnum`-generated mappers). Synthetic functions don't have a
     * `KSFunctionDeclaration` yet, so receiver/return types come from the
     * carried [com.blu3berry.kraft.model.TypeInfo]. Generated enum mappers
     * carry no opt-in markers themselves; the source/target classes already
     * propagate any `@RequiresOptIn` markers via the parent mapper, so we
     * skip opt-in collection here.
     */
    private fun buildSyntheticDelegate(key: ConverterTypeKey, entry: ConverterEntry.Synthetic): FunSpec {
        val receiverType: TypeName = entry.sourceTypeInfo.className
            .copy(nullable = entry.sourceTypeInfo.isNullable)
        val returnType: TypeName = entry.targetTypeInfo.className
            .copy(nullable = entry.targetTypeInfo.isNullable)

        val originalMember = MemberName(entry.packageName, entry.simpleName)

        return FunSpec.builder(DelegateNaming.delegateNameFor(key))
            .addModifiers(KModifier.PUBLIC)
            .addAnnotation(delegateAnnotation())
            .receiver(receiverType)
            .returns(returnType)
            .addStatement("return this.%M()", originalMember)
            .build()
    }

    private fun delegateAnnotation(): AnnotationSpec = AnnotationSpec.builder(
        ClassName("com.blu3berry.kraft.config", "KraftConverterDelegate")
    ).build()

    private fun collectMarkers(
        original: KSFunctionDeclaration,
        receiverType: KSType,
        returnType: KSType
    ): List<OptInMarker> {
        val targets = mutableListOf<KSAnnotated>(original)
        (receiverType.declaration as? KSClassDeclaration)?.let(targets::add)
        (returnType.declaration as? KSClassDeclaration)?.let(targets::add)
        return OptInMarkerCollector.collectFromAnnotated(targets)
    }

    @Suppress("SpreadOperator")
    private fun optInAnnotation(markers: List<OptInMarker>): AnnotationSpec? {
        if (markers.isEmpty()) return null
        val format = markers.joinToString(", ") { "%T::class" }
        val markerTypes = markers.map { ClassName(it.packageName, it.simpleName) }.toTypedArray()
        return AnnotationSpec.builder(ClassName("kotlin", "OptIn"))
            .addMember(format, *markerTypes)
            .build()
    }

    private fun sanitize(raw: String): String =
        raw.replace(Regex("[^A-Za-z0-9_]"), "_").ifBlank { "module" }

    private val converterKeyComparator: Comparator<ConverterTypeKey> = compareBy(
        { it.sourceFqName },
        { it.sourceNullable },
        { it.targetFqName },
        { it.targetNullable },
    )

    private fun contentHash(converters: List<ConverterEntry>): String {
        val sortedFqs = converters
            .map { entry -> "${entry.packageName}.${entry.simpleName}" }
            .sorted()
            .joinToString("|")
        // Stable, short, no external dependency; collisions are tolerated because
        // duplicate file names within one module already imply the same converter set.
        return "%08x".format(sortedFqs.hashCode())
    }
}
