package hu.nova.blu3berry.kraft.processor.util

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.ksp.writeTo

object CodeGenUtils {

    /**
     * Writes a FileSpec to disk using the KSP CodeGenerator
     */
    fun writeFile(
        codeGenerator: CodeGenerator,
        fileSpec: FileSpec,
        originatingFile: KSFile,
        aggregating: Boolean = false
    ) {
        fileSpec.writeTo(
            codeGenerator = codeGenerator,
            dependencies = Dependencies(aggregating, originatingFile)
        )
    }

    /**
     * Returns a standard disclaimer banner to include at the top of every generated file
     */
    fun generatedBanner(): String = 
        """
         * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
         *                                                                             *
         *   This file is generated by the KSP processor. Do not edit manually.        *
         *                                                                             *
         * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
         
        """.trimIndent()

    /**
     * Builds a file name in the standard convention: From_To_TypeMapper
     */
    fun buildFileName(fromClassName: String, toClassName: String, suffix: String = "Mapper"): String =
        "${fromClassName}_To_${toClassName}_$suffix"
}
