package com.blu3berry.kraft.config

/**
 * Internal marker for generated cross-module converter delegates.
 *
 * For every `@KraftConverter`-annotated function the user writes, the Kraft KSP
 * processor emits a `public` thin extension wrapper in package
 * `kraft.generated.registry`. The wrapper is annotated with `@KraftConverterDelegate`
 * so the consuming compilation can discover it — via package enumeration on JVM
 * classpaths, or by constructing the delegate's deterministic per-type-pair name on
 * KMP metadata (klib) classpaths — and re-build the (sourceType → targetType)
 * registry without having to scan the entire classpath.
 *
 * Users should not apply this annotation manually — declare your converters with
 * `@KraftConverter` and let the processor generate the delegates.
 *
 * @param moduleId The producing module's identity (the `kraft.moduleId` KSP option
 *                 when set, otherwise the generated registry file's hash suffix).
 *                 Delegates for the same type pair share the same function name by
 *                 design, so this is what lets ambiguity diagnostics name the two
 *                 conflicting modules instead of printing one FQN twice. Blank on
 *                 delegates generated by older Kraft versions; diagnostics then fall
 *                 back to the function's qualified name.
 */
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.BINARY)
annotation class KraftConverterDelegate(val moduleId: String = "")
